---

- include_vars: "{{ansible_distribution}}.yml"

- name: bootstrap epel-release install
  copy: src=mongodb-org-3.0.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644

- name: install the latest version of MongoDB
  yum: name=mongodb-org state=present
